{
 "title": "iot_grafana",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "HVAC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'HVAC1'  FROM hvac a WHERE a.`device` = 'HVAC1' GROUP BY a.`dtime`;"
    },
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'HVAC2'  FROM hvac a WHERE a.`device` = 'HVAC2' GROUP BY a.`dtime`;"
    }
   ]
  },
  {
   "title": "HVAC Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM `hvac` v\r\n-- where v.device = 'HVAC1'\r\nORDER BY v.dtime asc;"
    }
   ]
  },
  {
   "title": "MiAC Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM `miac` v\r\n-- where v.device = 'HVAC1'\r\nORDER BY v.dtime asc;"
    }
   ]
  },
  {
   "title": "MiAC",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'MiAC1'  FROM miac a WHERE a.`device` = 'MiAC1' GROUP BY a.`dtime`;"
    },
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'MiAC2'  FROM miac a WHERE a.`device` = 'MiAC2' GROUP BY a.`dtime`;"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'TH1'  FROM th a WHERE a.`device` = 'TH1' GROUP BY a.`dtime`;"
    },
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'TH2'  FROM th a WHERE a.`device` = 'TH2' GROUP BY a.`dtime`;"
    }
   ]
  },
  {
   "title": "Temperature Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "rawSql": "SELECT *\r\nFROM `th` v\r\n-- where v.device = 'HVAC1'\r\nORDER BY v.dtime asc;"
    }
   ]
  },
  {
   "title": "Rejected Event Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "rawSql": "\r\n SELECT DATE_FORMAT(v.dtime_received,'%Y-%m-%d') AS \"Received_Date\"\r\n, v.dtime_event, v.reading\r\nFROM `rejectedevents` v\r\n-- where v.device = 'HVAC1'\r\nORDER BY v.dtime_event asc;"
    }
   ]
  },
  {
   "title": "Rejected Events",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "rawSql": "SELECT a.`dtime_event`, reading AS 'Rejected Events'  FROM rejectedevents a ;"
    }
   ]
  },
  {
   "title": "ETOT",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'etot'  FROM etot a GROUP BY a.`dtime`;"
    }
   ]
  },
  {
   "title": "ETOT Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(v.dtime,'%Y-%m-%d') dtime, v.reading\r\nFROM `etot` v\r\n-- where v.device = 'HVAC1'\r\nORDER BY v.dtime asc;"
    }
   ]
  },
  {
   "title": "Water Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(dtime,'%Y-%m-%d') AS dtime, arrival_status, SUM(reading) AS TotalReading, MIN(reading) AS MinReading, MAX(reading) AS MaxReading\r\nFROM water\r\nGROUP BY DATE_FORMAT(dtime,'%Y-%m-%d'), arrival_status\r\norder by DATE_FORMAT(dtime,'%Y-%m-%d') asc;"
    }
   ]
  },
  {
   "title": "Sum of Water Reading",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  arrival_status, SUM(reading) AS TotalReading\r\nFROM water\r\nGROUP BY arrival_status;"
    }
   ]
  },
  {
   "title": "Water",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'rejected'  FROM water a WHERE a.`arrival_status` = 'rejected';"
    },
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'late'  FROM water a WHERE a.`arrival_status` = 'late' ;"
    },
    {
     "rawSql": "SELECT a.`dtime`, reading AS 'ontime'  FROM water a WHERE a.`arrival_status` = 'ontime';"
    }
   ]
  },
  {
   "title": "WTOT",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(dtime,'%m-%d') as dtime, reading AS 'wtot'  FROM wtot a GROUP BY a.`dtime`;"
    }
   ]
  },
  {
   "title": "MOV",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "rawSql": "SELECT DATE_FORMAT(dtime,'%m-%d') as dtime, day_count AS 'movementsumday'  FROM movementsumday a ;"
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 92 },
   "targets": [
    {
     "rawSql": "SELECT DATE(DATE_FORMAT(dtime,'%Y-%m-%d')) AS time_sec, COUNT(*) AS 'Time'  \r\nFROM alarms a \r\nWHERE a.`alarm_trigger` = 'Time' \r\nGROUP BY DATE(DATE_FORMAT(dtime,'%Y-%m-%d'));"
    },
    {
     "rawSql": "SELECT DATE(DATE_FORMAT(dtime,'%Y-%m-%d')) AS `dtime`, COUNT(*) AS 'Energy'  \r\nFROM alarms a \r\nWHERE a.`alarm_trigger` = 'Energy' \r\nGROUP BY DATE(DATE_FORMAT(dtime,'%Y-%m-%d'));"
    },
    {
     "rawSql": "SELECT DATE(DATE_FORMAT(dtime,'%Y-%m-%d')) AS `dtime`, COUNT(*) AS 'Energy Time'  \r\nFROM alarms a \r\nWHERE a.`alarm_trigger` = 'Energy Time' \r\nGROUP BY DATE(DATE_FORMAT(dtime,'%Y-%m-%d'));"
    }
   ]
  },
  {
   "title": "Alarm by Triggers",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 92 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  alarm_trigger, SUM(dtime) AS TotalReading\r\nFROM alarms\r\nGROUP BY alarm_trigger;"
    }
   ]
  }
 ]
}